services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
  server:
    build: ../packages/server
    image: hexrush-server:latest
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017/hexrush
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
  client:
    build: ../packages/client
    image: hexrush-client:latest
    depends_on:
      - server
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../packages/client/dist:/usr/share/nginx/html:ro
    depends_on:
      - client
      - server
volumes:
  mongo-data:
